/*
UPDATE [SIADI].[SIADI].[TB_PLANO_TRABALHO]
SET [NOM_NIVELESCOLAR] = '2'




SELECT	*
FROM	[SIADI].[SIADI].[TB_PLANO_TRABALHO]



SELECT
	o.name,
	m.definition
FROM sys.sql_modules m
	INNER JOIN sys.sysobjects o
		ON m.object_id   = o.Id
WHERE definition LIKE '%backup%'



SELECT	*
FROM	sys.schemas
*/
USE INMETRO

SELECT
	b.name [SCHEMA],
	a.name [OBJECT],
	c.definition [SQL]
FROM sys.objects a
	INNER JOIN sys.schemas b
		ON a.schema_id = b.schema_id
	INNER JOIN sys.sql_modules c
		ON a.object_id = c.object_id
WHERE b.name <> 'CONTROLEACESSO'
AND	c.definition LIKE '%CONTROLEACESSO%'





/*
BASE SIADI
CORPORATIVO--------------------------------------------------------
SIADI.FU_RETORNA_TIPO_DE_CHEFIA
SIADI.AUX_CADASTRAR_USUARIO_CONTROLEACESSO_SIADI
SIADI.FU_RETORNA_MATRICULA_CHEFE
SIADI.FU_RETORNA_MATRICULA_CHEFE_UOS_FILHAS
SIADI.FU_RETORNA_TIPO_CHEFIA

CONTROLEACESSO-----------------------------------------------------
SIADI.AUX_CADASTRAR_USUARIO_CONTROLEACESSO_SIADI


BASE INMETRO
CORPORATIVO--------------------------------------------------------
SIGRH.PU_SIADI_RETORNA_INFORMACOES_SERVIDOR_POR_IDT_MATRICULA_SIAPE
SIGRH.PU_SIADI_RETORNA_SERVIDOR_POR_IDT
SIGRH.PU_SIADI_RETORNA_SUBORDINADOS_DIRETOS_POR_CDN_UO
SIGRH.PU_SIADI_RETORNA_TODOS_SERVIDORES_ATIVOS
SIGRH.PU_SIADI_RETORNA_TODOS_SUBORDINADOS_POR_CDN_UO
SIGRH.PU_EXTRATOR_TB_PESSOA_FISICA_FORMACAO_TITULACAO
SIGRH.PU_EXTRATOR_TB_LOTACAO_ESTAGIARIO_UO
SIGRH.PU_EXTRATOR_TB_LOTACAO_SERVIDOR_UO
SIGRH.-- Apagar 11.06.2015 VW_UO_UP
SIGRH.VW_CONSULTA_UO_UP
SIGRH.VW_REL_RELACAO_RENDIMENTOS_DESCONTOS_POR_ASSUNTO_CALCULO
SIGRH.VW_CONSULTA_UP_DE_UO
SIGRH.VW_REL_RELACAO_SERVIDORES

*/


